apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db2
  namespace: manual-flask-app
spec:
  selector:
    matchLabels:
      app: mongo-db2
  template:
    metadata:
      labels:
        app: mongo-db2
    spec:
      containers:
      - name: mongo-db2
        image: mongo
        env: 
        - name: "MONGO_INITDB_ROOT_USERNAME"
          value: "admin"
        - name: "MONGO_INITDB_ROOT_PASSWORD"
          value: "dbgudwn1!"
        resources:
          limits:
            memory: "512Mi"
            cpu: "100m"
        ports:
        - name: mongo
          containerPort: 27017
        volumeMounts: 
          - name: mongo-db-storage
            mountPath: /data/db
      volumes:
      - name: mongo-db-storage
        hostPath:
          path: /home/youhyeongju/mongodb2
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db2
  namespace: manual-flask-app
spec:
  selector:
    app: mongo-db2
  ports:
  - port: 27018
    targetPort: 27017
